### ISSUE TITLE
importing es6 into webpack/config.js throws an error

### ISSUE THREAD

**Issue by alisonailea** [a-tarasyuk/rr-boilerplate#2]
src/utils/styleUtils/vars/font.js

```
export const baseFont = 16;
export const baseLineHeight = 22;
```

webpack/config.js

```
import cssMap from 'postcss-map';
import * as varMap from '../src/utils/styleUtils/vars/font.js';

postcss: (webpack) => {
    return [
         cssMap({
            maps: [varMap]
        })
    ];
}
```

error

```
/src/utils/styleUtils/vars/font.js:
export var baseFont = 16;
^^^^^^

SyntaxError: Unexpected reserved word
```

**Comment by a-tarasyuk** [comment]
@alisonailea Thanks for your report. This error occurs because you are trying to import file from `src` folder. For `webpack` and `src` there are two different `babel` configs,  - there is related issue https://github.com/webpack/webpack.js.org/issues/154 why it was done. As a workaround you can rename your file from `font.js` to `font.json` and add your font variables as json 

```
{
  "baseFont": 16,
  "baseLineHeight": 22
}
```

```
import varMap from '../src/utils/styleUtils/vars/font.json';
```
